language: android

android:
  components:
    - platform-tools
    - android-27
  licenses:
    - android-sdk-license-.+

install:
  - echo yes | sdkmanager "platforms"

scripts:
  - ./gradlew assemble
