language: android
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - EMULATOR_API_LEVEL=23

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - android-$EMULATOR_API_LEVEL
    - extra-android-support
    - sys-img-$ANDROID_ABI-android-$EMULATOR_API_LEVEL
  licenses:
    - android-sdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.3"

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

scripts:
  - ./gradlew build
